language: ruby
rvm:
- 2.2.3
services:
- postgresql
before_install:
- openssl aes-256-cbc -K $encrypted_5cdc469a064a_key -iv $encrypted_5cdc469a064a_iv
  -in do_jcfrails_deploy.enc -out do_jcfrails_deploy -d
- rm digital-ocean-deployer-key.enc
- chmod 600 digital-ocean-deployer-key
- mv digital-ocean-deployer-key ~/.ssh/id_rsa
script:
- RAILS_ENV=test bundle exec rake db:migrate --trace
- bundle exec rake db:test:prepare
- bundle exec rake
before_script:
- cp config/database.yml.travis config/database.yml
- psql -c 'create database "jcfausto-com_test"' -U postgres
- echo -e "Host jcfausto.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
after_success:
- bash lib/scripts/deploy.sh
