language:  ruby
rvm:
  - 2.2.3
services:
  - postgresql
before_install:
- openssl aes-256-cbc -K $encrypted_8f8c45d03da0_key -iv $encrypted_8f8c45d03da0_iv
  -in digital-ocean-deployer-key.enc -out digital-ocean-deployer-key -d
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database "jcfausto-com_test"' -U postgres